
package Tela;

import Classes.Diretor;
import Classes.Funcionario;
import Classes.Gestor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaFuncionario extends javax.swing.JFrame {


    public TelaFuncionario() {
 
                initComponents();
    }

            Object [] dados;
            ArrayList <Funcionario> funcionarios=new ArrayList<>();
    
    
    
    
   public void addiconaGestor(){
       Gestor g=new Gestor(this.txtnome.getText(),Double.valueOf(this.txtSalarioBase.getText()), 0);
     g.calcularSalario();
     funcionarios.add(g);
     
     
   }
    public void addiconaDiretor(){
        Diretor d=new Diretor(this.txtnome.getText(),Double.valueOf(this.txtSalarioBase.getText()), 0);
    d.calcularSalario();
     funcionarios.add(d);
     
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        btnCriar = new javax.swing.JToggleButton();
        btnAtualizar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        txtSalarioBase = new javax.swing.JTextField();
        lblRef = new javax.swing.JLabel();
        txtSalarioTotal = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regitro de Produtos");
        setMinimumSize(new java.awt.Dimension(672, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("salario Base");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cargo");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("salarioTotal");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCriar.setText("criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtSalarioBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioBaseActionPerformed(evt);
            }
        });

        lblRef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRef.setText("Nome");
        lblRef.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSalarioTotal.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRef, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(txtCargo))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalarioBase, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtSalarioTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnCriar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRef)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtSalarioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar))
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 671, 190);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        jTableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cargo", "SalarioBase", "SalarioTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 190, 670, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if(jTableCadastro.getSelectedRow()!= -1){
            jTableCadastro.setValueAt(txtnome.getText(), jTableCadastro.getSelectedRow(), 0);
            jTableCadastro.setValueAt(txtSalarioBase.getText(), jTableCadastro.getSelectedRow(), 1);
            jTableCadastro.setValueAt(txtCargo.getText(), jTableCadastro.getSelectedRow(), 2);
            jTableCadastro.setValueAt(txtSalarioTotal.getText(), jTableCadastro.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    
    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        DefaultTableModel tabela1= (DefaultTableModel)jTableCadastro.getModel() ;//criando a tabela
        txtCargo.getText().toLowerCase();
        if (txtCargo.getText().equals("gestor")) {
            JOptionPane.showMessageDialog(null, "entrei no metodo");
            addiconaGestor();
          this.dados = new Object[]{txtnome.getText(), txtSalarioBase.getText(), txtCargo.getText(), txtSalarioTotal.getText()};
             tabela1.addRow(dados);
        }else if (txtCargo.getText().equals("director")) {
            JOptionPane.showMessageDialog(null, "entrei no metodo director");
            addiconaDiretor();
             this.dados = new Object[]{txtnome.getText(), txtSalarioBase.getText(), txtCargo.getText(), txtSalarioTotal.getText()};
///cria um objecto que vai armazenar as linhas da tabela
            tabela1.addRow(dados);//adicionando a linha na tabela
        }else{
            this.dados = new Object[]{txtnome.getText(), txtSalarioBase.getText(), txtCargo.getText(), txtSalarioTotal.getText()};
///cria um objecto que vai armazenar as linhas da tabela
            tabela1.addRow(dados);//adicionando a linha na tabela
        }
  
  
    }//GEN-LAST:event_btnCriarActionPerformed

    private void txtSalarioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioBaseActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (jTableCadastro.getSelectedRow()!=-1) {//se a linha for selecionada
            DefaultTableModel tabela1=(DefaultTableModel) jTableCadastro.getModel();
            tabela1.removeRow(jTableCadastro.getSelectedRow());
           
        }else{
             JOptionPane.showMessageDialog(null, "selecione uma lista");
        }
                
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jTableCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroMouseClicked
      if(jTableCadastro.getSelectedRow()!= -1){
          txtnome.setText(jTableCadastro.getValueAt(jTableCadastro.getSelectedRow(), 0).toString());
          txtSalarioBase.setText(jTableCadastro.getValueAt(jTableCadastro.getSelectedRow(), 1).toString());
          txtCargo.setText(jTableCadastro.getValueAt(jTableCadastro.getSelectedRow(), 2).toString());
          txtSalarioTotal.setText(jTableCadastro.getValueAt(jTableCadastro.getSelectedRow(), 3).toString());
      }
    }//GEN-LAST:event_jTableCadastroMouseClicked

    /**tabel
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAtualizar;
    private javax.swing.JToggleButton btnCriar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastro;
    private javax.swing.JLabel lblRef;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtSalarioBase;
    private javax.swing.JTextField txtSalarioTotal;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
